apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-temporary-registry
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-temporary-registry
    capacity: 1
    expires: 24h
