apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-temporary-registry
spec:
  title: Temporary Registry
  description: Provides access to a temporary image registry.
  url: https://github.com/eduk8s-tests/lab-temporary-registry
  content:
    files: github.com/eduk8s-tests/lab-temporary-registry
  session:
    namespaces:
      budget: x-small
    applications:
      terminal:
        enabled: false
      registry:
        enabled: true
    env:
    - name: DEFAULT_PAGE
      value: /workshop/
